spring.application.name=studyhub

# JSF
joinfaces.faces.development-project-stage=Development
joinfaces.faces.project-stage=Development

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/studyhub
spring.datasource.username=postgres
spring.datasource.password=teovoinea2004
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=study_hub

#LIQUIBASE
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=false
spring.liquibase.default-schema=study_hub

#GOOGLE SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=usedforwebsites2004@gmail.com
spring.mail.password=uyun vzey ggnd mzwl

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.default-encoding=UTF-8

#OTHERS
server.servlet.session.cookie.http-only=true
joinfaces.faces.redirect-with-xml-extension=false

logging.level.org.springframework.security=DEBUG
logging.level.org.joinfaces=DEBUG

spring.mvc.pathmatch.use-suffix-pattern=false



